name: Bot Immobiliare Multi-Social

on:
  schedule:
    - cron: '30 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib requests gspread

      - name: Esegui Bot
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          FB_PAGE_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          YT2_CLIENT_ID: ${{ secrets.YT2_CLIENT_ID }}
          YT2_CLIENT_SECRET: ${{ secrets.YT2_CLIENT_SECRET }}
          YT2_REFRESH_TOKEN: ${{ secrets.YT2_REFRESH_TOKEN }}
          WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
        run: python bot.py
